# LOCAL DEV ONLY - DO NOT COMMIT REAL CREDENTIALS
# This file is gitignored.
spring.datasource.password=123

# Google OAuth2 Credentials
GOOGLE_CLIENT_ID=551538104963-oq8a3pp12bv2ntlb293jvpfiu2c2lvra.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
spring.security.oauth2.client.registration.google.client-id=551538104963-oq8a3pp12bv2ntlb293jvpfiu2c2lvra.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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